CREATE TABLE `ade_trade_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trade_id` varchar(64) NOT NULL,
	`model` varchar(16) NOT NULL,
	`ade_version` varchar(16) NOT NULL DEFAULT '2.0.0',
	`outcome` enum('WIN','LOSS','BREAKEVEN') NOT NULL,
	`r_multiple` decimal(8,4),
	`pnl` decimal(10,2),
	`norm_score` decimal(6,2),
	`confidence` varchar(16),
	`d_ms01` decimal(6,2),
	`d_ms02` decimal(6,2),
	`d_ms03` decimal(6,2),
	`d_ms04` decimal(6,2),
	`d_ms05` decimal(6,2),
	`d_eq01` decimal(6,2),
	`d_eq02` decimal(6,2),
	`d_eq03` decimal(6,2),
	`d_tc01` decimal(6,2),
	`d_tc02` decimal(6,2),
	`d_si01` decimal(6,2),
	`d_si02` decimal(6,2),
	`d_si03` decimal(6,2),
	`d_cr01` decimal(6,2),
	`d_cr02` decimal(6,2),
	`raw_score` decimal(8,2),
	`raw_max` decimal(8,2),
	`session` varchar(32),
	`dow` int,
	`adx14` decimal(8,4),
	`atr14` decimal(12,4),
	`volcomp` decimal(8,4),
	`opened_at` timestamp NOT NULL,
	`closed_at` timestamp NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ade_trade_records_id` PRIMARY KEY(`id`),
	CONSTRAINT `ade_trade_records_trade_id_unique` UNIQUE(`trade_id`)
);
--> statement-breakpoint
CREATE TABLE `ade_version_governance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`version` varchar(16) NOT NULL,
	`sprint_number` int NOT NULL,
	`change_type` enum('INITIAL','WEIGHT_CHANGE','DIMENSION_ADD','DIMENSION_REMOVE','THRESHOLD_CHANGE','BUGFIX') NOT NULL,
	`description` text NOT NULL,
	`trades_analysed` int,
	`pf_before` decimal(8,4),
	`pf_after` decimal(8,4),
	`mc_pass_rate_before` decimal(6,4),
	`mc_pass_rate_after` decimal(6,4),
	`approved_by` varchar(64) NOT NULL DEFAULT 'OWNER',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ade_version_governance_id` PRIMARY KEY(`id`)
);
