CREATE TABLE `atlas_scheduled_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_name` varchar(64) NOT NULL,
	`description` text,
	`cron_expression` varchar(64) NOT NULL,
	`callback_path` varchar(128) NOT NULL,
	`schedule_cron_task_uid` varchar(65),
	`is_enabled` boolean DEFAULT true,
	`last_run_at` timestamp,
	`last_run_status` varchar(32),
	`last_run_duration_ms` int,
	`total_runs` int DEFAULT 0,
	`successful_runs` int DEFAULT 0,
	`failed_runs` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `atlas_scheduled_jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `atlas_scheduled_jobs_job_name_unique` UNIQUE(`job_name`)
);
--> statement-breakpoint
CREATE TABLE `daily_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`review_date` date NOT NULL,
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	`generated_by` varchar(32) NOT NULL DEFAULT 'HEARTBEAT',
	`generation_status` enum('SUCCESS','PARTIAL','FAILED') NOT NULL DEFAULT 'SUCCESS',
	`generation_error` text,
	`total_trades` int DEFAULT 0,
	`winning_trades` int DEFAULT 0,
	`losing_trades` int DEFAULT 0,
	`net_pnl` decimal(10,2),
	`gross_profit` decimal(10,2),
	`gross_loss` decimal(10,2),
	`win_rate` decimal(6,4),
	`expectancy` decimal(10,2),
	`largest_winner` decimal(10,2),
	`largest_loser` decimal(10,2),
	`report_json` json NOT NULL,
	`notification_sent` boolean DEFAULT false,
	`notification_sent_at` timestamp,
	CONSTRAINT `daily_reviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rolling_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`review_date` date NOT NULL,
	`window` enum('7D','30D','90D','LIFETIME') NOT NULL,
	`trade_count` int DEFAULT 0,
	`win_count` int DEFAULT 0,
	`loss_count` int DEFAULT 0,
	`win_rate` decimal(6,4),
	`profit_factor` decimal(8,4),
	`expectancy` decimal(10,2),
	`avg_r` decimal(8,4),
	`net_pnl` decimal(10,2),
	`max_drawdown` decimal(10,2),
	`sb1_trade_count` int DEFAULT 0,
	`sb1_win_rate` decimal(6,4),
	`sb1_profit_factor` decimal(8,4),
	`sb1_net_pnl` decimal(10,2),
	`sb1_avg_ras` decimal(6,2),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rolling_performance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sb1_paper_trades` (
	`id` varchar(64) NOT NULL,
	`symbol` varchar(16) NOT NULL DEFAULT 'MNQ1!',
	`direction` enum('LONG','SHORT') NOT NULL,
	`status` enum('OPEN','CLOSED','CANCELLED') NOT NULL DEFAULT 'OPEN',
	`entry` decimal(12,4),
	`stop` decimal(12,4),
	`target` decimal(12,4),
	`exit_price` decimal(12,4),
	`exit_reason` varchar(64),
	`contracts` int DEFAULT 1,
	`risk_dollars` decimal(10,2),
	`pnl` decimal(10,2),
	`r_multiple` decimal(8,4),
	`mfe` decimal(10,2),
	`mae` decimal(10,2),
	`opened_at` timestamp NOT NULL DEFAULT (now()),
	`closed_at` timestamp,
	`holding_time_ms` bigint,
	`session` varchar(32),
	`dow` int,
	`ras` decimal(6,2),
	`ras_activated` boolean DEFAULT false,
	`regime_cluster` int,
	`ras_c1_pd_range_atr` decimal(6,2),
	`ras_c2_pd_position` decimal(6,2),
	`ras_c3_overnight_gap` decimal(6,2),
	`ras_c4_chop` decimal(6,2),
	`ras_c5_atr_expansion` decimal(6,2),
	`ras_c6_vwap_dist` decimal(6,2),
	`ras_c7_ema_slope` decimal(6,2),
	`ras_c8_ema_dist` decimal(6,2),
	`ras_c9_trend_pers` decimal(6,2),
	`feature_pd_range_atr` decimal(8,4),
	`feature_pd_position` decimal(8,4),
	`feature_overnight_gap` decimal(8,4),
	`feature_chop` decimal(8,4),
	`feature_atr_expansion` decimal(8,4),
	`feature_vwap_dist` decimal(8,4),
	`feature_ema_slope` decimal(8,4),
	`feature_ema_dist` decimal(8,4),
	`feature_trend_pers` decimal(8,4),
	`pipeline_run_id` varchar(128),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `sb1_paper_trades_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sb1_ras_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bar_time` varchar(32) NOT NULL,
	`symbol` varchar(16) NOT NULL DEFAULT 'MNQ1!',
	`ras` decimal(6,2) NOT NULL,
	`ras_activated` boolean NOT NULL DEFAULT false,
	`activation_reason` varchar(128),
	`feature_pd_range_atr` decimal(8,4),
	`feature_pd_position` decimal(8,4),
	`feature_overnight_gap` decimal(8,4),
	`feature_chop` decimal(8,4),
	`feature_atr_expansion` decimal(8,4),
	`feature_vwap_dist` decimal(8,4),
	`feature_ema_slope` decimal(8,4),
	`feature_ema_dist` decimal(8,4),
	`feature_trend_pers` decimal(8,4),
	`pipeline_run_id` varchar(128),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `sb1_ras_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sb1_rejected_signals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bar_time` varchar(32) NOT NULL,
	`symbol` varchar(16) NOT NULL DEFAULT 'MNQ1!',
	`direction` enum('LONG','SHORT') NOT NULL,
	`ras` decimal(6,2) NOT NULL,
	`rejection_reason` varchar(128) NOT NULL,
	`feature_pd_range_atr` decimal(8,4),
	`feature_chop` decimal(8,4),
	`feature_atr_expansion` decimal(8,4),
	`feature_vwap_dist` decimal(8,4),
	`hypothetical_pnl` decimal(10,2),
	`hypothetical_outcome` varchar(16),
	`pipeline_run_id` varchar(128),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `sb1_rejected_signals_id` PRIMARY KEY(`id`)
);
