CREATE TABLE `ard_bar_observations` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`bar_time` datetime NOT NULL,
	`symbol` varchar(16) NOT NULL DEFAULT 'MNQ1!',
	`timeframe` varchar(8) NOT NULL DEFAULT '5',
	`event_id` varchar(64),
	`idempotency_key` varchar(128),
	`session` varchar(16),
	`day_of_week` varchar(16),
	`open` decimal(12,4),
	`high` decimal(12,4),
	`low` decimal(12,4),
	`close` decimal(12,4),
	`volume` int,
	`atr` decimal(10,4),
	`adx` decimal(8,4),
	`chop` decimal(8,4),
	`vwap` decimal(12,4),
	`rsi` decimal(8,4),
	`ema9` decimal(12,4),
	`ema21` decimal(12,4),
	`ema50` decimal(12,4),
	`ema200` decimal(12,4),
	`ema9_slope` decimal(10,6),
	`ema21_slope` decimal(10,6),
	`ema50_slope` decimal(10,6),
	`trend_direction` varchar(8),
	`ema_alignment` varchar(16),
	`volatility_state` varchar(16),
	`compression_state` varchar(16),
	`regime_classification` varchar(32),
	`prev_day_high` decimal(12,4),
	`prev_day_low` decimal(12,4),
	`prev_day_close` decimal(12,4),
	`prev_day_range` decimal(10,4),
	`overnight_gap` decimal(10,4),
	`price_vs_prev_day` varchar(16),
	`a1_eligible` boolean DEFAULT false,
	`a3_eligible` boolean DEFAULT false,
	`b1_eligible` boolean DEFAULT false,
	`sb1_eligible` boolean DEFAULT false,
	`ade_edge_score` decimal(8,4),
	`ade_candidate` varchar(8),
	`ari_decision` varchar(16),
	`tvl_decision` varchar(16),
	`sb1_ras` decimal(6,2),
	`sb1_ras_activated` boolean DEFAULT false,
	`has_open_position` boolean DEFAULT false,
	`open_position_direction` varchar(8),
	`open_position_entry` decimal(12,4),
	`open_position_unrealized_pnl` decimal(10,2),
	`pipeline_run_id` varchar(64),
	`pipeline_health` varchar(16),
	`schema_version` varchar(16) DEFAULT '1.0.0',
	`received_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ard_bar_observations_id` PRIMARY KEY(`id`),
	CONSTRAINT `ard_bar_observations_event_id_unique` UNIQUE(`event_id`),
	CONSTRAINT `ard_bar_observations_idempotency_key_unique` UNIQUE(`idempotency_key`)
);
--> statement-breakpoint
CREATE TABLE `ard_candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`candidate_id` varchar(32) NOT NULL,
	`title` varchar(128) NOT NULL,
	`discovery_date` date NOT NULL,
	`hypothesis` text NOT NULL,
	`direction` varchar(16),
	`horizon` varchar(32),
	`feature_definition` text,
	`occurrences` int DEFAULT 0,
	`sample_size` int DEFAULT 0,
	`supporting_evidence` text,
	`contradicting_evidence` text,
	`estimated_effect_size` decimal(8,4),
	`novelty_score` decimal(6,4),
	`portfolio_fit` varchar(32),
	`risk_concerns` text,
	`required_validation` text,
	`status` varchar(16) NOT NULL DEFAULT 'Observed',
	`promoted_to_model` varchar(16),
	`rejection_reason` text,
	`priority_score` decimal(6,4),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ard_candidates_id` PRIMARY KEY(`id`),
	CONSTRAINT `ard_candidates_candidate_id_unique` UNIQUE(`candidate_id`)
);
--> statement-breakpoint
CREATE TABLE `oracle_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prediction_id` varchar(64) NOT NULL,
	`trade_id` varchar(64),
	`model_id` varchar(16),
	`timestamp` datetime NOT NULL,
	`direction` varchar(8),
	`entry_price` decimal(12,4),
	`stop_price` decimal(12,4),
	`target_price` decimal(12,4),
	`expected_win_prob` decimal(6,4),
	`expected_r` decimal(8,4),
	`expected_holding_time_min` int,
	`expected_mfe` decimal(10,4),
	`expected_mae` decimal(10,4),
	`expected_exit_type` varchar(32),
	`expected_trend_duration` varchar(32),
	`expected_volatility` varchar(16),
	`expected_regime` varchar(32),
	`ade_edge_score` decimal(8,4),
	`ari_state` varchar(16),
	`tvl_status` varchar(16),
	`sb1_ras` decimal(6,2),
	`top_contributors` text,
	`reasoning_summary` text,
	`atlas_version` varchar(32),
	`git_commit` varchar(64),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `oracle_predictions_id` PRIMARY KEY(`id`),
	CONSTRAINT `oracle_predictions_prediction_id_unique` UNIQUE(`prediction_id`)
);
--> statement-breakpoint
CREATE TABLE `oracle_reality` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prediction_id` varchar(64) NOT NULL,
	`trade_id` varchar(64),
	`actual_result` varchar(16),
	`actual_r` decimal(8,4),
	`actual_pnl` decimal(10,2),
	`actual_holding_time_min` int,
	`actual_mfe` decimal(10,4),
	`actual_mae` decimal(10,4),
	`actual_exit_type` varchar(32),
	`actual_regime_evolution` text,
	`actual_volatility` varchar(16),
	`actual_session_behaviour` text,
	`unexpected_events` text,
	`data_quality_issues` text,
	`execution_issues` text,
	`r_error` decimal(8,4),
	`holding_time_error` int,
	`mfe_error` decimal(10,4),
	`mae_error` decimal(10,4),
	`regime_match_correct` boolean,
	`exit_type_match_correct` boolean,
	`win_prob_calibration_bin` decimal(6,4),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `oracle_reality_id` PRIMARY KEY(`id`),
	CONSTRAINT `oracle_reality_prediction_id_unique` UNIQUE(`prediction_id`)
);
--> statement-breakpoint
CREATE TABLE `oracle_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`score_date` date NOT NULL,
	`model_id` varchar(16) NOT NULL,
	`window_type` varchar(16) NOT NULL,
	`calibration_accuracy` decimal(6,2),
	`prediction_accuracy` decimal(6,2),
	`reasoning_consistency` decimal(6,2),
	`regime_recognition` decimal(6,2),
	`confidence_reliability` decimal(6,2),
	`decision_quality` decimal(6,2),
	`report_completeness` decimal(6,2),
	`oracle_score` decimal(6,2),
	`brier_score` decimal(8,6),
	`log_loss` decimal(8,6),
	`expected_calibration_error` decimal(8,6),
	`trade_count` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `oracle_scores_id` PRIMARY KEY(`id`)
);
