CREATE TABLE `atlas_memory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`memory_id` varchar(64) NOT NULL,
	`event_id` varchar(80) NOT NULL,
	`idempotency_key` varchar(64) NOT NULL,
	`schema_version` varchar(16) NOT NULL DEFAULT '1.1.0',
	`atlas_version` varchar(32),
	`symbol` varchar(16) NOT NULL DEFAULT 'MNQ1!',
	`timeframe` varchar(8) NOT NULL DEFAULT '5',
	`bar_index` int,
	`pipeline_run_id` varchar(64),
	`bar_time` bigint NOT NULL,
	`bar_time_et` varchar(32),
	`session` varchar(8),
	`day_of_week` varchar(4),
	`hour_et` int,
	`is_rth` boolean DEFAULT false,
	`open` decimal(10,2),
	`high` decimal(10,2),
	`low` decimal(10,2),
	`close` decimal(10,2),
	`volume` decimal(14,0),
	`atr` decimal(10,4),
	`atr5` decimal(10,4),
	`atr_expansion` decimal(8,4),
	`atr_percentile` decimal(6,2),
	`adx` decimal(6,2),
	`adx_trending` boolean DEFAULT false,
	`chop` decimal(6,2),
	`rsi` decimal(6,2),
	`vwap` decimal(10,2),
	`dist_vwap` decimal(10,2),
	`ema9` decimal(10,2),
	`ema21` decimal(10,2),
	`ema50` decimal(10,2),
	`ema200` decimal(10,2),
	`ema9_slope` decimal(10,6),
	`ema21_slope` decimal(10,6),
	`ema50_slope` decimal(10,6),
	`ema_alignment` varchar(8),
	`trend_direction` varchar(12),
	`volatility_state` varchar(16),
	`compression_state` varchar(16),
	`regime_classification` varchar(24),
	`prev_day_high` decimal(10,2),
	`prev_day_low` decimal(10,2),
	`prev_day_close` decimal(10,2),
	`prev_day_range` decimal(10,2),
	`prev_day_range_atr` decimal(8,4),
	`overnight_gap` decimal(8,4),
	`price_vs_prev_day` varchar(16),
	`a1_eligible` boolean DEFAULT false,
	`a3_eligible` boolean DEFAULT false,
	`b1_eligible` boolean DEFAULT false,
	`sb1_eligible` boolean DEFAULT false,
	`active_models` varchar(32),
	`sb1_ras` decimal(6,2),
	`sb1_ras_activated` boolean DEFAULT false,
	`pipeline_health` varchar(16) DEFAULT 'OK',
	`obs_count` int,
	`error_count` int DEFAULT 0,
	`module_version` varchar(16),
	`sprint` int,
	`received_at` timestamp NOT NULL DEFAULT (now()),
	`raw_payload` text,
	CONSTRAINT `atlas_memory_id` PRIMARY KEY(`id`),
	CONSTRAINT `atlas_memory_memory_id_unique` UNIQUE(`memory_id`),
	CONSTRAINT `atlas_memory_idempotency_key_unique` UNIQUE(`idempotency_key`)
);
