CREATE TABLE `tie_clusters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cluster_id` varchar(64) NOT NULL,
	`cluster_name` varchar(128) NOT NULL,
	`description` text,
	`sequence_types` text,
	`occurrences` int NOT NULL DEFAULT 0,
	`avg_pf` decimal(6,3),
	`avg_duration_bars` decimal(6,2),
	`avg_reversal_probability` decimal(5,2),
	`confidence` decimal(5,2),
	`dominant_regime` varchar(32),
	`dominant_session` varchar(16),
	`behavioural_fingerprint` text,
	`last_updated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tie_clusters_id` PRIMARY KEY(`id`),
	CONSTRAINT `tie_clusters_cluster_id_unique` UNIQUE(`cluster_id`)
);
--> statement-breakpoint
CREATE TABLE `tie_oracle_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prediction_id` varchar(64) NOT NULL,
	`sequence_id` varchar(64) NOT NULL,
	`predicted_outcome` varchar(128),
	`predicted_r` decimal(6,3),
	`predicted_duration_bars` int,
	`predicted_confidence` decimal(5,2),
	`actual_outcome` varchar(128),
	`actual_r` decimal(6,3),
	`actual_duration_bars` int,
	`prediction_error` decimal(6,3),
	`confidence_calibration` decimal(5,2),
	`sequence_reliability` decimal(5,2),
	`surprise_index` decimal(5,2),
	`status` enum('pending','resolved','expired') NOT NULL DEFAULT 'pending',
	`predicted_at` bigint,
	`resolved_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tie_oracle_predictions_id` PRIMARY KEY(`id`),
	CONSTRAINT `tie_oracle_predictions_prediction_id_unique` UNIQUE(`prediction_id`)
);
--> statement-breakpoint
CREATE TABLE `tie_research_candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`candidate_id` varchar(64) NOT NULL,
	`sequence_id` varchar(64),
	`evidence_score` decimal(5,2),
	`occurrence_count` int NOT NULL DEFAULT 0,
	`statistical_confidence` decimal(5,2),
	`research_priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`certification_status` enum('candidate','under_review','certified','rejected') NOT NULL DEFAULT 'candidate',
	`first_seen` bigint,
	`last_seen` bigint,
	`behavioural_signature` text,
	`notes` text,
	`discovered_by` varchar(64) DEFAULT 'TIE-AUTO',
	`promoted_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tie_research_candidates_id` PRIMARY KEY(`id`),
	CONSTRAINT `tie_research_candidates_candidate_id_unique` UNIQUE(`candidate_id`)
);
--> statement-breakpoint
CREATE TABLE `tie_sequence_library` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sequence_type` varchar(64) NOT NULL,
	`display_name` varchar(128) NOT NULL,
	`description` text,
	`first_observed` bigint,
	`last_observed` bigint,
	`occurrences` int NOT NULL DEFAULT 0,
	`win_rate` decimal(5,2),
	`avg_r` decimal(6,3),
	`avg_duration_bars` decimal(6,2),
	`avg_mfe` decimal(8,4),
	`avg_mae` decimal(8,4),
	`probability_distribution` text,
	`typical_exit_behaviour` text,
	`best_models` varchar(256),
	`worst_models` varchar(256),
	`oracle_prediction_accuracy` decimal(5,2),
	`research_status` enum('candidate','active','certified','deprecated') NOT NULL DEFAULT 'candidate',
	`constitutional_note` text,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tie_sequence_library_id` PRIMARY KEY(`id`),
	CONSTRAINT `tie_sequence_library_sequence_type_unique` UNIQUE(`sequence_type`)
);
--> statement-breakpoint
CREATE TABLE `tie_sequences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sequence_id` varchar(64) NOT NULL,
	`sequence_type` varchar(64) NOT NULL,
	`label` varchar(128),
	`start_time` bigint NOT NULL,
	`end_time` bigint,
	`start_bar_index` int,
	`end_bar_index` int,
	`duration_bars` int,
	`symbol` varchar(20) NOT NULL DEFAULT 'MNQ1!',
	`timeframe` varchar(8) NOT NULL DEFAULT '5',
	`session` varchar(8),
	`dominant_trend` varchar(32),
	`volatility_profile` varchar(32),
	`vwap_behaviour` varchar(64),
	`ema_behaviour` varchar(64),
	`adx_evolution` varchar(32),
	`atr_evolution` varchar(32),
	`chop_evolution` varchar(32),
	`regime` varchar(32),
	`market_structure` varchar(64),
	`completion_status` enum('active','completed','terminated','branched') NOT NULL DEFAULT 'active',
	`confidence` decimal(5,2),
	`cluster_id` varchar(64),
	`oracle_prediction_id` varchar(64),
	`experience_score` decimal(5,2),
	`similarity_cluster` varchar(64),
	`similarity_pct` decimal(5,2),
	`expected_outcome` varchar(128),
	`expected_duration_bars` int,
	`expected_r` decimal(6,3),
	`behaviour_story` text,
	`bar_snapshots` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tie_sequences_id` PRIMARY KEY(`id`),
	CONSTRAINT `tie_sequences_sequence_id_unique` UNIQUE(`sequence_id`)
);
