CREATE TABLE `darwin_backtests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`backtest_id` varchar(64) NOT NULL,
	`candidate_id` varchar(64) NOT NULL,
	`stage` varchar(64) NOT NULL,
	`total_trades` int,
	`win_rate` decimal(5,2),
	`profit_factor` decimal(6,3),
	`net_profit` decimal(12,2),
	`max_drawdown` decimal(12,2),
	`max_loss_streak` int,
	`expectancy` decimal(8,2),
	`sharpe_ratio` decimal(6,3),
	`mc_profit_probability` decimal(5,2),
	`dd_violation_risk` decimal(5,2),
	`parameter_stability_score` decimal(5,2),
	`robustness_score` decimal(5,2),
	`passed` boolean NOT NULL DEFAULT false,
	`failure_reason` text,
	`raw_results` json,
	`run_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_backtests_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_backtests_backtest_id_unique` UNIQUE(`backtest_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`candidate_id` varchar(64) NOT NULL,
	`behaviour_class` varchar(64) NOT NULL,
	`behaviour_description` text,
	`occurrence_count` int NOT NULL DEFAULT 0,
	`statistical_significance` decimal(5,4),
	`confidence` decimal(5,2),
	`estimated_win_rate` decimal(5,2),
	`estimated_pf` decimal(6,3),
	`estimated_frequency` int,
	`estimated_pcs` decimal(5,2),
	`estimated_correlation` decimal(5,3),
	`research_priority` int NOT NULL DEFAULT 99,
	`evidence_score` decimal(5,2),
	`supporting_regimes` text,
	`supporting_sessions` text,
	`human_explanation` text,
	`governance_stage` varchar(64) NOT NULL DEFAULT 'HYPOTHESIS',
	`rejection_reason` text,
	`promoted_at` bigint,
	`first_observed` bigint,
	`last_observed` bigint,
	`discovered_by` varchar(64) NOT NULL DEFAULT 'DARWIN',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `darwin_candidates_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_candidates_candidate_id_unique` UNIQUE(`candidate_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_self_eval` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eval_id` varchar(64) NOT NULL,
	`period_start` bigint NOT NULL,
	`period_end` bigint NOT NULL,
	`hypotheses_created` int NOT NULL DEFAULT 0,
	`hypotheses_validated` int NOT NULL DEFAULT 0,
	`hypotheses_rejected` int NOT NULL DEFAULT 0,
	`false_discoveries` int NOT NULL DEFAULT 0,
	`prediction_accuracy` decimal(5,2),
	`research_efficiency` decimal(5,2),
	`avg_time_to_certification_days` decimal(6,2),
	`discovery_rate` decimal(5,2),
	`quality_score` decimal(5,2),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_self_eval_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_self_eval_eval_id_unique` UNIQUE(`eval_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_weekly_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_id` varchar(64) NOT NULL,
	`week_start` date NOT NULL,
	`week_end` date NOT NULL,
	`new_observations` int NOT NULL DEFAULT 0,
	`behavioural_changes_detected` int NOT NULL DEFAULT 0,
	`candidates_created` int NOT NULL DEFAULT 0,
	`candidates_rejected` int NOT NULL DEFAULT 0,
	`candidates_promoted` int NOT NULL DEFAULT 0,
	`portfolio_health_score` decimal(5,2),
	`coverage_score` decimal(5,2),
	`highest_priority_candidate` varchar(64),
	`highest_confidence_opportunity` varchar(64),
	`estimated_portfolio_impact` text,
	`oracle_accuracy` decimal(5,2),
	`research_velocity` decimal(5,2),
	`full_report_markdown` text,
	`generated_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_weekly_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_weekly_reports_report_id_unique` UNIQUE(`report_id`)
);
