CREATE TABLE `darwin_exec_briefings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`briefing_id` varchar(64) NOT NULL,
	`briefing_date` bigint NOT NULL,
	`portfolio_health_score` decimal(5,2),
	`portfolio_coverage_score` decimal(5,2),
	`atlas_memory_growth` int NOT NULL DEFAULT 0,
	`darwin_health_score` decimal(5,2),
	`oracle_accuracy` decimal(5,2),
	`new_observations_week` int NOT NULL DEFAULT 0,
	`total_candidates` int NOT NULL DEFAULT 0,
	`promotion_candidates` int NOT NULL DEFAULT 0,
	`rejected_candidates` int NOT NULL DEFAULT 0,
	`highest_confidence_discovery` varchar(128),
	`highest_confidence_score` decimal(5,2),
	`highest_expected_gain_candidate` varchar(128),
	`highest_priority_research` text,
	`model_health_summary` text,
	`behaviour_coverage_map` text,
	`estimated_future_improvement` decimal(5,2),
	`full_briefing_markdown` text,
	`read_time_seconds` int NOT NULL DEFAULT 45,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_exec_briefings_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_exec_briefings_briefing_id_unique` UNIQUE(`briefing_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_job_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` varchar(64) NOT NULL,
	`job_type` varchar(64) NOT NULL,
	`layer` int NOT NULL DEFAULT 1,
	`status` varchar(32) NOT NULL DEFAULT 'PENDING',
	`priority` int NOT NULL DEFAULT 5,
	`payload` text,
	`reference_key` varchar(128),
	`scheduled_at` bigint NOT NULL,
	`started_at` bigint,
	`completed_at` bigint,
	`duration_ms` int,
	`error_message` text,
	`retry_count` int NOT NULL DEFAULT 0,
	`max_retries` int NOT NULL DEFAULT 3,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_job_queue_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_job_queue_job_id_unique` UNIQUE(`job_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_research_memory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`memory_id` varchar(64) NOT NULL,
	`candidate_id` varchar(64),
	`behaviour_class` varchar(64),
	`hypothesis_description` text NOT NULL,
	`proposed_reason` text,
	`supporting_evidence` text,
	`backtest_summary` text,
	`monte_carlo_summary` text,
	`robustness_score` decimal(5,2),
	`oracle_findings` text,
	`portfolio_impact` text,
	`final_outcome` varchar(32),
	`rejection_reasons` text,
	`lessons_learned` text,
	`research_hours_estimate` decimal(6,2),
	`certification_probability` decimal(5,2),
	`expected_portfolio_contribution` decimal(5,2),
	`roi_score` decimal(5,2),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `darwin_research_memory_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_research_memory_memory_id_unique` UNIQUE(`memory_id`)
);
