CREATE TABLE `candle_certifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cert_id` varchar(64) NOT NULL,
	`symbol` varchar(16) NOT NULL DEFAULT 'MNQ1!',
	`expected_bar_time` bigint NOT NULL,
	`actual_bar_time` bigint,
	`session` varchar(16),
	`is_rth` boolean DEFAULT false,
	`status` enum('CERTIFIED','MISSING','DUPLICATE','INVALID','RECOVERED') NOT NULL DEFAULT 'MISSING',
	`timestamp_correct` boolean,
	`no_duplicate` boolean,
	`no_predecessor_gap` boolean,
	`ohlcv_valid` boolean,
	`written_to_memory` boolean,
	`analysis_complete` boolean,
	`linked_to_market_laws` boolean,
	`ingestion_latency_ms` int,
	`gap_from_previous_ms` bigint,
	`atlas_memory_id` int,
	`pipeline_report_id` varchar(64),
	`recovery_attempted` boolean DEFAULT false,
	`recovery_succeeded` boolean DEFAULT false,
	`recovery_method` varchar(64),
	`notes` text,
	`certified_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `candle_certifications_id` PRIMARY KEY(`id`),
	CONSTRAINT `candle_certifications_cert_id_unique` UNIQUE(`cert_id`)
);
--> statement-breakpoint
CREATE TABLE `candle_gap_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gap_id` varchar(64) NOT NULL,
	`symbol` varchar(16) NOT NULL DEFAULT 'MNQ1!',
	`gap_start_time` bigint NOT NULL,
	`gap_end_time` bigint,
	`expected_bars` int NOT NULL DEFAULT 1,
	`missing_bars` int NOT NULL DEFAULT 1,
	`gap_duration_ms` bigint,
	`gap_duration_minutes` decimal(8,2),
	`is_rth_gap` boolean DEFAULT false,
	`session` varchar(16),
	`cause_classification` enum('MARKET_CLOSED','TRADINGVIEW_ALERT_MISCONFIGURED','WEBHOOK_TIMEOUT','SERVER_RESTART','DUPLICATE_SUPPRESSED','UNKNOWN','HOLIDAY') DEFAULT 'UNKNOWN',
	`cause_notes` text,
	`recovered` boolean DEFAULT false,
	`recovery_method` varchar(64),
	`owner_notified` boolean DEFAULT false,
	`detected_at` timestamp NOT NULL DEFAULT (now()),
	`resolved_at` timestamp,
	CONSTRAINT `candle_gap_log_id` PRIMARY KEY(`id`),
	CONSTRAINT `candle_gap_log_gap_id_unique` UNIQUE(`gap_id`)
);
--> statement-breakpoint
CREATE TABLE `live_concordance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`concordance_id` varchar(64) NOT NULL,
	`window_days` int NOT NULL,
	`computed_at` timestamp NOT NULL DEFAULT (now()),
	`live_range_rate` decimal(5,4),
	`live_transition_rate` decimal(5,4),
	`live_volatile_rate` decimal(5,4),
	`historical_range_rate` decimal(5,4) DEFAULT '0.5100',
	`historical_transition_rate` decimal(5,4) DEFAULT '0.4480',
	`historical_volatile_rate` decimal(5,4) DEFAULT '0.0370',
	`regime_divergence_score` decimal(5,4),
	`live_win_rate` decimal(5,4),
	`live_profit_factor` decimal(6,4),
	`historical_win_rate` decimal(5,4) DEFAULT '0.5010',
	`historical_profit_factor` decimal(6,4) DEFAULT '1.5870',
	`performance_divergence_score` decimal(5,4),
	`live_avg_atr` decimal(8,4),
	`historical_avg_atr` decimal(8,4) DEFAULT '12.5000',
	`volatility_divergence_score` decimal(5,4),
	`overall_concordance_score` decimal(5,2),
	`darwin_review_triggered` boolean DEFAULT false,
	`darwin_review_reason` text,
	`total_live_days` int NOT NULL DEFAULT 0,
	`total_live_bars` int NOT NULL DEFAULT 0,
	CONSTRAINT `live_concordance_id` PRIMARY KEY(`id`),
	CONSTRAINT `live_concordance_concordance_id_unique` UNIQUE(`concordance_id`)
);
--> statement-breakpoint
CREATE TABLE `market_laws` (
	`id` int AUTO_INCREMENT NOT NULL,
	`law_id` varchar(16) NOT NULL,
	`title` varchar(128) NOT NULL,
	`statement` text NOT NULL,
	`causal_explanation` text,
	`discovered_sprint` int NOT NULL,
	`discovery_date` bigint NOT NULL,
	`historical_bars_supporting` int NOT NULL DEFAULT 0,
	`historical_bars_contradicting` int NOT NULL DEFAULT 0,
	`live_observations_consistent` int NOT NULL DEFAULT 0,
	`live_observations_contradicting` int NOT NULL DEFAULT 0,
	`confidence_score` decimal(5,2) NOT NULL DEFAULT '0.00',
	`admission_status` enum('PROVISIONAL','ADMITTED','CHALLENGED','REVISED','RETIRED') NOT NULL DEFAULT 'PROVISIONAL',
	`last_challenged_at` bigint,
	`last_challenge_description` text,
	`related_laws` varchar(128),
	`related_models` varchar(128),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `market_laws_id` PRIMARY KEY(`id`),
	CONSTRAINT `market_laws_law_id_unique` UNIQUE(`law_id`)
);
--> statement-breakpoint
CREATE TABLE `morning_briefs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brief_id` varchar(64) NOT NULL,
	`brief_date` varchar(10) NOT NULL,
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	`latest_commit` varchar(64),
	`latest_commit_message` text,
	`outstanding_engineering_tasks` int NOT NULL DEFAULT 0,
	`system_health_score` decimal(5,2),
	`last_webhook_received_at` bigint,
	`hours_since_last_webhook` decimal(6,2),
	`regime_probability_range` decimal(5,2),
	`regime_probability_transition` decimal(5,2),
	`regime_probability_volatile` decimal(5,2),
	`expected_regime` varchar(24),
	`eligible_models` varchar(128),
	`expected_trade_count` int,
	`total_risk_budget` decimal(10,2),
	`research_running_overnight` text,
	`owner_actions_required` text,
	`full_brief_markdown` text,
	`notification_sent` boolean DEFAULT false,
	CONSTRAINT `morning_briefs_id` PRIMARY KEY(`id`),
	CONSTRAINT `morning_briefs_brief_id_unique` UNIQUE(`brief_id`)
);
--> statement-breakpoint
CREATE TABLE `pipeline_health_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_id` varchar(64) NOT NULL,
	`event_type` enum('WEBHOOK_SILENCE','WEBHOOK_RECOVERED','CANDLE_GAP_DETECTED','CANDLE_GAP_RESOLVED','SERVER_RESTART','DB_WRITE_FAILURE','DB_WRITE_RECOVERED','MEMORY_WRITE_FAILURE','SELF_HEAL_ATTEMPTED','SELF_HEAL_SUCCEEDED','SELF_HEAL_FAILED','OWNER_NOTIFIED','DARWIN_REVIEW_TRIGGERED') NOT NULL,
	`severity` enum('INFO','WARNING','CRITICAL') NOT NULL DEFAULT 'INFO',
	`description` text NOT NULL,
	`affected_component` varchar(64),
	`last_successful_at` bigint,
	`silence_duration_ms` bigint,
	`auto_recovered` boolean DEFAULT false,
	`owner_notified` boolean DEFAULT false,
	`resolved_at` timestamp,
	`metadata` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `pipeline_health_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `pipeline_health_events_event_id_unique` UNIQUE(`event_id`)
);
