CREATE TABLE `behaviour_library` (
	`id` int AUTO_INCREMENT NOT NULL,
	`behaviour_id` varchar(32) NOT NULL,
	`behaviour_name` varchar(128) NOT NULL,
	`description` text,
	`total_observations` int NOT NULL DEFAULT 0,
	`continuation_count` int NOT NULL DEFAULT 0,
	`reversal_count` int NOT NULL DEFAULT 0,
	`continuation_rate` decimal(6,4),
	`avg_atr` decimal(10,4),
	`avg_volume` decimal(14,2),
	`regime_breakdown` text,
	`session_breakdown` text,
	`last_observed_at` bigint,
	`last_updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `behaviour_library_id` PRIMARY KEY(`id`),
	CONSTRAINT `behaviour_library_behaviour_id_unique` UNIQUE(`behaviour_id`)
);
--> statement-breakpoint
CREATE TABLE `live_learning_cert_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`session_date` varchar(16) NOT NULL,
	`session_start` bigint,
	`session_end` bigint,
	`expected_candles` int DEFAULT 78,
	`received_candles` int DEFAULT 0,
	`missing_candles` int DEFAULT 0,
	`duplicate_candles` int DEFAULT 0,
	`certified_candles` int DEFAULT 0,
	`failed_candles` int DEFAULT 0,
	`coverage_pct` decimal(6,3),
	`avg_latency_ms` int,
	`max_latency_ms` int,
	`min_latency_ms` int,
	`uptime_pct` decimal(6,3),
	`gate_results` text,
	`behaviour_library_updates` int DEFAULT 0,
	`sequence_library_updates` int DEFAULT 0,
	`market_law_evaluations` int DEFAULT 0,
	`market_laws_reinforced` int DEFAULT 0,
	`market_laws_challenged` int DEFAULT 0,
	`darwin_memory_writes` int DEFAULT 0,
	`portfolio_intel_updates` int DEFAULT 0,
	`certification_status` varchar(16) DEFAULT 'PENDING',
	`certification_notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `live_learning_cert_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `live_learning_cert_sessions_session_date_unique` UNIQUE(`session_date`)
);
--> statement-breakpoint
CREATE TABLE `portfolio_intelligence_inputs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bar_time` bigint NOT NULL,
	`symbol` varchar(16) NOT NULL,
	`session` varchar(32),
	`regime` varchar(32),
	`regime_probabilities` text,
	`eligible_models` text,
	`active_model` varchar(16),
	`signal_quality` int,
	`daily_trade_count` int DEFAULT 0,
	`daily_pnl` decimal(12,2),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `portfolio_intelligence_inputs_id` PRIMARY KEY(`id`)
);
