CREATE TABLE `darwin_cro_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_id` varchar(64) NOT NULL,
	`report_date` bigint NOT NULL,
	`week_start` bigint NOT NULL,
	`week_end` bigint NOT NULL,
	`research_completed` int NOT NULL DEFAULT 0,
	`research_started` int NOT NULL DEFAULT 0,
	`research_rejected` int NOT NULL DEFAULT 0,
	`research_promoted` int NOT NULL DEFAULT 0,
	`market_laws_updated` int NOT NULL DEFAULT 0,
	`behaviours_discovered` int NOT NULL DEFAULT 0,
	`portfolio_improvement_score` decimal(5,2),
	`regime_coverage_score` decimal(5,2),
	`session_coverage_score` decimal(5,2),
	`correlation_reduction_score` decimal(5,2),
	`top_priority_research` text,
	`owner_actions_required` text,
	`darwin_efficiency_score` decimal(5,2),
	`compute_utilisation_pct` decimal(5,2),
	`full_report_markdown` text,
	`read_time_seconds` int NOT NULL DEFAULT 120,
	`generated_by` varchar(32) NOT NULL DEFAULT 'DARWIN_CRO',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_cro_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_cro_reports_report_id_unique` UNIQUE(`report_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_promotion_gates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gate_id` varchar(64) NOT NULL,
	`research_id` varchar(64) NOT NULL,
	`candidate_id` varchar(64),
	`from_stage` varchar(32) NOT NULL,
	`to_stage` varchar(32) NOT NULL,
	`decision` varchar(16) NOT NULL,
	`evidence_score` decimal(6,2),
	`confidence_score` decimal(5,2),
	`portfolio_value` decimal(5,2),
	`occurrences` int,
	`win_rate` decimal(5,2),
	`profit_factor` decimal(5,2),
	`mc_pass_rate` decimal(5,2),
	`min_evidence_required` decimal(6,2),
	`min_confidence_required` decimal(5,2),
	`decision_rationale` text NOT NULL,
	`evaluated_by` varchar(32) NOT NULL DEFAULT 'DARWIN',
	`evaluated_at` bigint NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_promotion_gates_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_promotion_gates_gate_id_unique` UNIQUE(`gate_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_rejection_registry` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rejection_id` varchar(64) NOT NULL,
	`research_id` varchar(64),
	`candidate_id` varchar(64),
	`hypothesis_summary` text NOT NULL,
	`behaviour_class` varchar(64),
	`rejection_stage` varchar(32) NOT NULL,
	`rejection_reason` text NOT NULL,
	`reason_code` varchar(64) NOT NULL DEFAULT 'INSUFFICIENT_EVIDENCE',
	`evidence_at_rejection` decimal(6,2),
	`confidence_at_rejection` decimal(5,2),
	`lesson_learned` text,
	`reconsider_conditions` text,
	`compute_hours_spent` decimal(6,2) DEFAULT '0.00',
	`rejected_at` bigint NOT NULL,
	`rejected_by` varchar(32) NOT NULL DEFAULT 'DARWIN',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_rejection_registry_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_rejection_registry_rejection_id_unique` UNIQUE(`rejection_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_research_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`research_id` varchar(64) NOT NULL,
	`origin` varchar(32) NOT NULL DEFAULT 'DARWIN',
	`hypothesis` text NOT NULL,
	`behaviour_class` varchar(64),
	`current_stage` varchar(32) NOT NULL DEFAULT 'OBSERVATION',
	`priority` int NOT NULL DEFAULT 50,
	`evidence_score` decimal(6,2) NOT NULL DEFAULT '0.00',
	`confidence` decimal(5,2) NOT NULL DEFAULT '0.00',
	`portfolio_value` decimal(5,2) NOT NULL DEFAULT '0.00',
	`computational_cost` int NOT NULL DEFAULT 5,
	`expected_research_value` decimal(7,4) NOT NULL DEFAULT '0.0000',
	`dependencies` text,
	`last_reviewed` bigint,
	`next_scheduled_review` bigint,
	`target_regimes` varchar(128),
	`target_sessions` varchar(128),
	`estimated_correlation` decimal(5,4),
	`live_observations` int NOT NULL DEFAULT 0,
	`historical_observations` int NOT NULL DEFAULT 0,
	`linked_candidate_id` varchar(64),
	`status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
	`block_reason` text,
	`novelty_score` decimal(5,2) NOT NULL DEFAULT '50.00',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `darwin_research_queue_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_research_queue_research_id_unique` UNIQUE(`research_id`)
);
--> statement-breakpoint
CREATE TABLE `darwin_work_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`work_id` varchar(64) NOT NULL,
	`work_type` varchar(64) NOT NULL,
	`description` text NOT NULL,
	`rationale` text,
	`target_research_id` varchar(64),
	`target_candidate_id` varchar(64),
	`outcome` varchar(32) NOT NULL DEFAULT 'PENDING',
	`outcome_details` text,
	`duration_ms` int,
	`scheduled_priority` int NOT NULL DEFAULT 5,
	`layer` int NOT NULL DEFAULT 3,
	`started_at` bigint NOT NULL,
	`completed_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `darwin_work_log_id` PRIMARY KEY(`id`),
	CONSTRAINT `darwin_work_log_work_id_unique` UNIQUE(`work_id`)
);
