CREATE TABLE `live_learning_sessions_monitor` (
	`id` int AUTO_INCREMENT NOT NULL,
	`session_date` date NOT NULL,
	`session_number` int NOT NULL,
	`cert_window_id` varchar(64),
	`bars_expected` int DEFAULT 78,
	`bars_received` int DEFAULT 0,
	`bars_missing` int DEFAULT 0,
	`bars_duplicate` int DEFAULT 0,
	`models_evaluated` varchar(64),
	`models_eligible` varchar(64),
	`signals_generated` int DEFAULT 0,
	`trades_opened` int DEFAULT 0,
	`trades_closed` int DEFAULT 0,
	`pnl_by_model` text,
	`session_pnl` decimal(10,2) DEFAULT '0',
	`certification_status` enum('PENDING','CLEAN','CONTAMINATED','INCOMPLETE') NOT NULL DEFAULT 'PENDING',
	`contamination_reason` text,
	`owner_action_required` text,
	`rth_open` bigint,
	`rth_close` bigint,
	`report_generated_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `live_learning_sessions_monitor_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `monitor_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bar_time` bigint NOT NULL,
	`bar_time_et` varchar(32),
	`session` varchar(32),
	`is_rth` boolean DEFAULT false,
	`adx` decimal(8,4),
	`regime_classification` varchar(32),
	`integrity_ok` boolean DEFAULT true,
	`gap_detected` boolean DEFAULT false,
	`gap_minutes` int,
	`duplicate_detected` boolean DEFAULT false,
	`integrity_notes` text,
	`a1_eligible` boolean DEFAULT false,
	`a1_reason` varchar(256),
	`a3_eligible` boolean DEFAULT false,
	`a3_reason` varchar(256),
	`sb1_eligible` boolean DEFAULT false,
	`sb1_reason` varchar(256),
	`orb1_eligible` boolean DEFAULT false,
	`orb1_reason` varchar(256),
	`b1_eligible` boolean DEFAULT false,
	`b1_reason` varchar(256),
	`active_models` varchar(64),
	`signal_model` varchar(16),
	`signal_direction` varchar(8),
	`atlas_memory_id` int,
	`evaluated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `monitor_evaluations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `session_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`session_date` date NOT NULL,
	`report_type` varchar(32) NOT NULL DEFAULT 'RTH_SESSION',
	`status` enum('CLEAN','DEGRADED','FAILED') NOT NULL DEFAULT 'CLEAN',
	`bars_expected` int,
	`bars_received` int,
	`bars_missing` int,
	`signals_generated` int DEFAULT 0,
	`trades_opened` int DEFAULT 0,
	`trades_closed` int DEFAULT 0,
	`session_pnl` decimal(10,2) DEFAULT '0',
	`certification_status` varchar(32),
	`owner_action_required` text,
	`report_json` text NOT NULL,
	`github_commit_sha` varchar(64),
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `session_reports_id` PRIMARY KEY(`id`)
);
