CREATE TABLE `wf_daily_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_date` date NOT NULL,
	`session_number` int NOT NULL,
	`pipeline_health` enum('OK','DEGRADED','FAILED') NOT NULL DEFAULT 'OK',
	`dashboard_health` enum('OK','DEGRADED','FAILED') NOT NULL DEFAULT 'OK',
	`data_integrity` enum('OK','DEGRADED','FAILED') NOT NULL DEFAULT 'OK',
	`bars_received` int DEFAULT 0,
	`bars_expected` int DEFAULT 78,
	`signals_generated` int DEFAULT 0,
	`trades_opened` int DEFAULT 0,
	`trades_closed` int DEFAULT 0,
	`session_wins` int DEFAULT 0,
	`session_losses` int DEFAULT 0,
	`session_pnl` decimal(10,2) DEFAULT '0',
	`session_drawdown` decimal(10,2) DEFAULT '0',
	`live_win_rate` decimal(6,4),
	`live_pf` decimal(8,4),
	`live_expectancy` decimal(10,2),
	`live_max_dd` decimal(10,2),
	`benchmark_win_rate` decimal(6,4) DEFAULT '0.753',
	`benchmark_pf` decimal(8,4) DEFAULT '4.985',
	`drift_detected` boolean DEFAULT false,
	`drift_alert_count` int DEFAULT 0,
	`cum_trade_count` int DEFAULT 0,
	`calendar_days_elapsed` int DEFAULT 0,
	`promotion_gate_status` varchar(32),
	`estimated_completion_date` date,
	`report_json` text,
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `wf_daily_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `wf_daily_reports_report_date_unique` UNIQUE(`report_date`)
);
--> statement-breakpoint
CREATE TABLE `wf_drift_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`alert_type` varchar(64) NOT NULL,
	`severity` enum('WARN','CRITICAL') NOT NULL DEFAULT 'WARN',
	`benchmark_value` decimal(10,4),
	`live_value` decimal(10,4),
	`deviation_pct` decimal(8,4),
	`trade_count` int,
	`session_date` date,
	`description` text NOT NULL,
	`resolved` boolean DEFAULT false,
	`resolution` text,
	`resolved_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `wf_drift_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wf_live_trades` (
	`id` varchar(64) NOT NULL,
	`hypothesis_id` varchar(32) NOT NULL DEFAULT 'DARWIN-S109-001',
	`hypothesis_version` varchar(8) NOT NULL DEFAULT '1.0',
	`trade_date` date NOT NULL,
	`bar_time_et` varchar(32) NOT NULL,
	`session` varchar(16) NOT NULL DEFAULT 'RTH',
	`regime` varchar(32),
	`ov_inventory` varchar(8),
	`vwap_slope` decimal(10,6),
	`rsi14` decimal(8,4),
	`atr14` decimal(12,4),
	`vwap_deviation` decimal(12,4),
	`filter_ov_inventory` boolean NOT NULL DEFAULT false,
	`filter_vwap_slope` boolean NOT NULL DEFAULT false,
	`filter_rsi` boolean NOT NULL DEFAULT false,
	`direction` enum('LONG','SHORT') NOT NULL,
	`entry_price` decimal(12,4),
	`stop_price` decimal(12,4),
	`target_price` decimal(12,4),
	`exit_price` decimal(12,4),
	`exit_reason` varchar(32),
	`risk_dollars` decimal(10,2) NOT NULL DEFAULT '450',
	`status` enum('OPEN','CLOSED') NOT NULL DEFAULT 'OPEN',
	`outcome` enum('WIN','LOSS','BREAKEVEN'),
	`pnl_dollar` decimal(10,2),
	`pnl_r` decimal(8,4),
	`mfe` decimal(10,2),
	`mae` decimal(10,2),
	`holding_bars` int,
	`holding_ms` bigint,
	`opened_at` timestamp NOT NULL DEFAULT (now()),
	`closed_at` timestamp,
	`pipeline_run_id` varchar(128),
	`atlas_memory_bar_id` int,
	`provenance` enum('PAPER','BACKTEST','LIVE','TEST','CONTAMINATED') NOT NULL DEFAULT 'PAPER',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`immutable` boolean NOT NULL DEFAULT false,
	CONSTRAINT `wf_live_trades_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wf_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`session_date` date NOT NULL,
	`session_number` int NOT NULL,
	`bars_expected` int DEFAULT 78,
	`bars_received` int DEFAULT 0,
	`signals_evaluated` int DEFAULT 0,
	`signals_filtered` int DEFAULT 0,
	`trades_opened` int DEFAULT 0,
	`trades_closed` int DEFAULT 0,
	`wins` int DEFAULT 0,
	`losses` int DEFAULT 0,
	`session_pnl` decimal(10,2) DEFAULT '0',
	`cum_trades` int DEFAULT 0,
	`cum_wins` int DEFAULT 0,
	`cum_win_rate` decimal(6,4),
	`cum_pf` decimal(8,4),
	`cum_pnl` decimal(10,2) DEFAULT '0',
	`cum_max_dd` decimal(10,2) DEFAULT '0',
	`drift_detected` boolean DEFAULT false,
	`drift_alert_ids` text,
	`promotion_gate_status` enum('PENDING','IN_PROGRESS','PASSED','FAILED','SUSPENDED') NOT NULL DEFAULT 'PENDING',
	`daily_report_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wf_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `wf_sessions_session_date_unique` UNIQUE(`session_date`)
);
