CREATE TABLE `apex_account_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`snapshot_date` date NOT NULL,
	`starting_balance` decimal(12,2) NOT NULL DEFAULT '50000.00',
	`current_balance` decimal(12,2) NOT NULL,
	`current_equity` decimal(12,2) NOT NULL,
	`unrealised_pnl` decimal(10,2) NOT NULL DEFAULT '0.00',
	`daily_pnl` decimal(10,2) NOT NULL,
	`profit_target` decimal(10,2) NOT NULL DEFAULT '3000.00',
	`trailing_dd_limit` decimal(10,2) NOT NULL DEFAULT '2000.00',
	`peak_balance` decimal(12,2) NOT NULL,
	`trailing_threshold` decimal(12,2) NOT NULL,
	`remaining_trailing_dd` decimal(10,2) NOT NULL,
	`current_drawdown` decimal(10,2) NOT NULL,
	`total_profit` decimal(10,2) NOT NULL,
	`pass_progress` decimal(5,2) NOT NULL,
	`trades_today` int NOT NULL DEFAULT 0,
	`total_trades` int NOT NULL DEFAULT 0,
	`evaluation_status` enum('ACTIVE','PASSED','FAILED','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
	`notes` text,
	CONSTRAINT `apex_account_snapshots_id` PRIMARY KEY(`id`),
	CONSTRAINT `apex_account_snapshots_snapshot_date_unique` UNIQUE(`snapshot_date`)
);
--> statement-breakpoint
CREATE TABLE `apex_trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`wf_trade_id` int,
	`hypothesis_id` varchar(32) NOT NULL DEFAULT 'DARWIN-S109-001',
	`hypothesis_version` varchar(16) NOT NULL DEFAULT '1.0',
	`trade_date` date NOT NULL,
	`direction` enum('LONG','SHORT') NOT NULL,
	`instrument` varchar(16) NOT NULL DEFAULT 'MNQ',
	`contracts` int NOT NULL DEFAULT 1,
	`atlas_signal_bar_time` bigint,
	`atlas_entry_price` decimal(10,2),
	`atlas_stop_price` decimal(10,2),
	`atlas_target_price` decimal(10,2),
	`atlas_atr14` decimal(10,4),
	`apex_entry_price` decimal(10,2) NOT NULL,
	`apex_entry_time` bigint,
	`apex_stop_price` decimal(10,2) NOT NULL,
	`apex_target_price` decimal(10,2) NOT NULL,
	`apex_exit_price` decimal(10,2),
	`apex_exit_time` bigint,
	`apex_exit_reason` enum('TARGET','STOP','TIME_STOP','MANUAL'),
	`apex_pnl` decimal(10,2),
	`apex_holding_bars` int,
	`entry_slippage_pts` decimal(8,4),
	`exit_slippage_pts` decimal(8,4),
	`pnl_difference` decimal(10,2),
	`outcome_match` boolean,
	`divergence_flag` enum('NONE','EXPECTED_SLIPPAGE','ELEVATED_SLIPPAGE','EXECUTION_ERROR','OUTCOME_DIVERGENCE','MISSING_TRADE','EXTRA_TRADE') DEFAULT 'NONE',
	`divergence_notes` text,
	`status` enum('OPEN','CLOSED') NOT NULL DEFAULT 'OPEN',
	`is_win` boolean,
	CONSTRAINT `apex_trades_id` PRIMARY KEY(`id`)
);
