CREATE TABLE `gap_candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dimension` varchar(64) NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text NOT NULL,
	`evidence` text,
	`impact_score` decimal(5,1) NOT NULL DEFAULT '0.0',
	`confidence_score` decimal(5,1) NOT NULL DEFAULT '0.0',
	`effort_estimate` varchar(32),
	`expected_benefit` text,
	`expected_risk_reduction` text,
	`priority_rank` int,
	`status` enum('OPEN','INVESTIGATING','RESOLVED','DEFERRED','REJECTED') NOT NULL DEFAULT 'OPEN',
	`related_strategy_id` varchar(32),
	`related_sprint_id` varchar(32),
	`resolved_at` bigint,
	`resolved_notes` text,
	`source_run_id` int,
	`auto_generated` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `gap_candidates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gap_discovery_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_date` varchar(16) NOT NULL,
	`week_start_date` varchar(16),
	`week_end_date` varchar(16),
	`total_gaps_identified` int NOT NULL DEFAULT 0,
	`new_gaps_this_week` int NOT NULL DEFAULT 0,
	`resolved_this_week` int NOT NULL DEFAULT 0,
	`open_gaps` int NOT NULL DEFAULT 0,
	`top_10_portfolio_gaps` text,
	`top_10_research_opps` text,
	`top_engineering_improvements` text,
	`top_execution_improvements` text,
	`top_dashboard_improvements` text,
	`autonomous_question_answers` text,
	`estimated_portfolio_improvement_pct` decimal(5,2),
	`recommended_next_priority` text,
	`analysis_data_json` text,
	`generated_at` bigint NOT NULL,
	`generation_duration_ms` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `gap_discovery_reports_id` PRIMARY KEY(`id`)
);
