"""
Atlas Databento Feed Adapter — Official DBN Fixtures
Sprint 123A.2 — Gate G2 Revision 3 (Final)

Provides factory functions for creating Databento SDK message objects
for use in tests. Fixtures are categorised into three tiers:

  TIER 1 — Synthetic SDK-constructed fixtures
    make_trade_msg()          → databento.TradeMsg (real SDK constructor)
    make_ohlcv_msg()          → databento.OHLCVMsg (real SDK constructor)
    make_symbol_mapping_msg() → databento.SymbolMappingMsg (real SDK constructor)

  TIER 2 — Official DBN-decoded fixture
    make_real_instrument_def_msg() → databento_dbn.InstrumentDefMsg decoded
                                     via DBNDecoder from mnq_definition_record.dbn

  TIER 3 — Spec-based mock (retained for backward compatibility)
    make_instrument_def_msg() → MagicMock(spec=databento.InstrumentDefMsg)

TIER 2 is the authoritative definition fixture for Gate G2 production-path
compatibility testing. TIER 3 is retained for tests that do not require
round-trip DBN decode fidelity.

All fixtures use MNQ (Micro Nasdaq futures) as the test instrument.
Timestamps use nanosecond precision to validate that precision is preserved
through the normalisation pipeline.

SECRET SAFETY
-------------
These fixtures MUST NOT contain any real API keys, bridge tokens, or
other secrets. All values are synthetic test data only.
No live Databento API connection is used. No real market data is present.

DBN FIXTURE PROVENANCE
----------------------
mnq_definition_record.dbn was generated by:
  1. Constructing a databento_dbn.InstrumentDefMsg with synthetic MNQ parameters.
  2. Encoding to DBN binary format via bytes(msg).
  3. Verifying round-trip decode via DBNDecoder produces identical field values.
  4. Writing the encoded bytes to mnq_definition_record.dbn.
  Generation script: /tmp/build_defn_fixture.py (committed in evidence document).
  No live API, no real market data, no secrets.
"""

from __future__ import annotations

import os
from pathlib import Path
from unittest.mock import MagicMock

import databento as db
import databento_dbn

# ── Test constants ─────────────────────────────────────────────────────────────

MNQ_INSTRUMENT_ID = 12345
MNQ_CANONICAL_SYMBOL = "MNQ1!"
MNQ_RAW_SYMBOL = "MNQM5"
MNQ_CONTINUOUS_SYMBOL = "MNQ.v.0"

# Nanosecond timestamp: 2023-11-14T22:13:20.000000000Z
SAMPLE_TS_EVENT_NS = 1_700_000_000_000_000_000
# ts_recv: +1 microsecond
SAMPLE_TS_RECV_NS = 1_700_000_000_001_000_000

# Expiry: 2025-05-30T00:00:00Z in nanoseconds
SAMPLE_EXPIRY_NS = 1_748_649_600_000_000_000

# Fixed-point price: 18500.25 USD (Databento uses 1e-9 scale factor)
SAMPLE_PRICE_INT = 18_500_250_000_000

# OHLCV prices in fixed-point
SAMPLE_OPEN_INT = 18_500_000_000_000   # 18500.00
SAMPLE_HIGH_INT = 18_510_000_000_000   # 18510.00
SAMPLE_LOW_INT = 18_490_000_000_000    # 18490.00
SAMPLE_CLOSE_INT = 18_505_000_000_000  # 18505.00
SAMPLE_VOLUME = 250

# Definition record constants
SAMPLE_MIN_PRICE_INC = 2_500_000    # 0.0025 USD in fixed-point (1e-9 scale)
SAMPLE_DISPLAY_FACTOR = 1_000_000_000  # 1.0 in fixed-point (1e-9 scale)

# Path to the official DBN-decoded fixture file
_FIXTURES_DIR = Path(__file__).parent
DBN_DEFINITION_FIXTURE_PATH = _FIXTURES_DIR / "mnq_definition_record.dbn"


# ── TIER 1: Synthetic SDK-constructed fixtures ─────────────────────────────────

def make_trade_msg(
    instrument_id: int = MNQ_INSTRUMENT_ID,
    ts_event_ns: int = SAMPLE_TS_EVENT_NS,
    price_int: int = SAMPLE_PRICE_INT,
    size: int = 1,
) -> db.TradeMsg:
    """
    TIER 1 — Synthetic SDK-constructed fixture.

    Create a real databento.TradeMsg for testing.
    Uses db.Action.TRADE and db.Side.BID enum values as required by the SDK.
    All values are synthetic test data — no real market data or secrets.
    """
    return db.TradeMsg(
        publisher_id=1,
        instrument_id=instrument_id,
        ts_event=ts_event_ns,
        price=price_int,
        size=size,
        action=db.Action.TRADE,
        side=db.Side.BID,
        depth=0,
        ts_recv=ts_event_ns + 1_000,  # 1 microsecond receive latency
    )


def make_ohlcv_msg(
    instrument_id: int = MNQ_INSTRUMENT_ID,
    ts_event_ns: int = SAMPLE_TS_EVENT_NS,
    open_int: int = SAMPLE_OPEN_INT,
    high_int: int = SAMPLE_HIGH_INT,
    low_int: int = SAMPLE_LOW_INT,
    close_int: int = SAMPLE_CLOSE_INT,
    volume: int = SAMPLE_VOLUME,
) -> db.OHLCVMsg:
    """
    TIER 1 — Synthetic SDK-constructed fixture.

    Create a real databento.OHLCVMsg for testing.
    rtype=34 corresponds to the ohlcv-1m schema RType value.
    All values are synthetic test data — no real market data or secrets.
    """
    return db.OHLCVMsg(
        rtype=34,  # RType.OHLCV_1M
        publisher_id=1,
        instrument_id=instrument_id,
        ts_event=ts_event_ns,
        open=open_int,
        high=high_int,
        low=low_int,
        close=close_int,
        volume=volume,
    )


def make_symbol_mapping_msg(
    instrument_id: int = MNQ_INSTRUMENT_ID,
    ts_event_ns: int = SAMPLE_TS_EVENT_NS,
    stype_in_symbol: str = MNQ_CONTINUOUS_SYMBOL,
    stype_out_symbol: str = MNQ_RAW_SYMBOL,
) -> db.SymbolMappingMsg:
    """
    TIER 1 — Synthetic SDK-constructed fixture.

    Create a real databento.SymbolMappingMsg for testing.
    Maps MNQ.v.0 (continuous) → MNQM5 (raw contract symbol).
    All values are synthetic test data — no real market data or secrets.
    """
    return db.SymbolMappingMsg(
        publisher_id=1,
        instrument_id=instrument_id,
        ts_event=ts_event_ns,
        stype_in=db.SType.CONTINUOUS,
        stype_in_symbol=stype_in_symbol,
        stype_out=db.SType.RAW_SYMBOL,
        stype_out_symbol=stype_out_symbol,
        start_ts=ts_event_ns,
        end_ts=0,  # 0 = no expiry
    )


# ── TIER 2: Official DBN-decoded fixture ──────────────────────────────────────

def make_real_instrument_def_msg() -> databento_dbn.InstrumentDefMsg:
    """
    TIER 2 — Official DBN-decoded fixture.

    Load and decode mnq_definition_record.dbn via the Databento DBNDecoder
    to produce a real databento_dbn.InstrumentDefMsg record.

    This is the authoritative definition fixture for Gate G2 production-path
    compatibility testing. The fixture file was generated by:
      1. Constructing a databento_dbn.InstrumentDefMsg with synthetic MNQ
         parameters using the real SDK constructor.
      2. Encoding to DBN binary format via bytes(msg).
      3. Verifying round-trip decode via DBNDecoder.
      4. Writing the encoded bytes to mnq_definition_record.dbn.

    No live Databento API connection is used. No real market data is present.
    No secrets are present in the fixture file or the decoded record.

    Returns
    -------
    databento_dbn.InstrumentDefMsg
        A real SDK-decoded InstrumentDefMsg record with the following values:
        - instrument_id: 12345
        - raw_symbol: "MNQM5"
        - asset: "MNQ"
        - currency: "USD"
        - instrument_class: InstrumentClass.FUTURE ('F')
        - min_price_increment: 2_500_000 (0.0025 USD at 1e-9 scale)
        - display_factor: 1_000_000_000 (1.0 at 1e-9 scale)
        - expiration: 1_748_649_600_000_000_000 (2025-05-30T00:00:00Z)
        - ts_event: 1_700_000_000_000_000_000 (2023-11-14T22:13:20Z)
        - ts_recv: 1_700_000_000_001_000_000 (+1 microsecond)
    """
    if not DBN_DEFINITION_FIXTURE_PATH.exists():
        raise FileNotFoundError(
            f"DBN definition fixture not found: {DBN_DEFINITION_FIXTURE_PATH}\n"
            "Run /tmp/build_defn_fixture.py to regenerate it."
        )
    raw_bytes = DBN_DEFINITION_FIXTURE_PATH.read_bytes()
    decoder = databento_dbn.DBNDecoder(has_metadata=False, ts_out=False)
    decoder.write(raw_bytes)
    records = decoder.decode()
    if not records:
        raise RuntimeError(
            f"DBNDecoder returned no records from {DBN_DEFINITION_FIXTURE_PATH}"
        )
    record = records[0]
    if not isinstance(record, databento_dbn.InstrumentDefMsg):
        raise TypeError(
            f"Expected InstrumentDefMsg, got {type(record).__name__}"
        )
    return record


# ── TIER 3: Spec-based mock (backward compatibility) ──────────────────────────

def make_instrument_def_msg(
    instrument_id: int = MNQ_INSTRUMENT_ID,
    raw_symbol: str = MNQ_RAW_SYMBOL,
    asset: str = "MNQ",
) -> MagicMock:
    """
    TIER 3 — Spec-based mock (retained for backward compatibility).

    Create a MagicMock(spec=db.InstrumentDefMsg) for testing.

    IMPORTANT: This mock does NOT exercise the real DBN decode path.
    For production-path compatibility testing, use make_real_instrument_def_msg()
    (TIER 2) instead.

    The spec ensures that attribute access on undefined fields raises
    AttributeError rather than silently returning a Mock, which would mask
    bugs in the normalisation code.

    All values are synthetic test data — no real market data or secrets.
    """
    mock = MagicMock(spec=db.InstrumentDefMsg)
    mock.instrument_id = instrument_id
    mock.raw_symbol = raw_symbol
    mock.asset = asset
    mock.instrument_class = "FUT"
    mock.currency = "USD"
    mock.min_price_increment = SAMPLE_MIN_PRICE_INC   # 0.0025 USD in fixed-point
    mock.display_factor = SAMPLE_DISPLAY_FACTOR        # 1.0 in fixed-point
    mock.expiration = 0
    mock.ts_recv = SAMPLE_TS_EVENT_NS + 1_000
    return mock
